name: hotfix

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'should publish npm package'
        required: true
        type: boolean
      deploy:
        description: 'should deploy to Expo'
        required: true
        type: boolean
      deploy-tag:
        description: 'deploy tag(like v1.0.0-hotfix.1)'
        required: true
        type: string

jobs:
  publish:
    if: ${{ inputs.publish }} == true
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build web
        run: yarn build-web

      - name: stable-publish
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          greater-version-only: true

  deploy:
    if: ${{ inputs.deploy }} == true
    uses: ./.github/workflows/deploy.yml
    with:
      update-args: --branch release --message ${{ inputs.deploy-tag }}
      environment: production
    secrets: inherit
